<!DOCTYPE html>
<html lang="vi" data-theme="light">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Vista Exam Hub - Ôn thi Tiếng Anh vào 10 THPT</title>
  <style>
    :root{
      --primary:#f97316;--primary2:#fb923c;--dark:#0f172a;--text:#1e293b;--muted:#64748b;
      --bg:#f8fafc;--card:rgba(255,255,255,.94);--soft:#f8fafc;--border:#e2e8f0;
      --green:#16a34a;--greenSoft:#dcfce7;--red:#dc2626;--redSoft:#fee2e2;--amber:#f59e0b;--amberSoft:#fef3c7;
      --shadow:0 18px 50px rgba(15,23,42,.10);--radius:26px;--radius2:18px;
    }
    [data-theme="dark"]{--dark:#f8fafc;--text:#e2e8f0;--muted:#94a3b8;--bg:#020617;--card:rgba(15,23,42,.95);--soft:#111827;--border:#334155;--shadow:0 18px 50px rgba(0,0,0,.28)}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;font-family:Arial,Helvetica,sans-serif;color:var(--text);min-height:100vh;background:radial-gradient(circle at top left,rgba(249,115,22,.16),transparent 30%),radial-gradient(circle at 90% 8%,rgba(59,130,246,.10),transparent 28%),linear-gradient(135deg,#fff7ed 0%,#fff 43%,#eff6ff 100%)}
    [data-theme="dark"] body{background:radial-gradient(circle at top left,rgba(249,115,22,.14),transparent 30%),radial-gradient(circle at 90% 8%,rgba(59,130,246,.12),transparent 28%),linear-gradient(135deg,#020617 0%,#0f172a 55%,#111827 100%)}
    header{padding:14px 18px;border-bottom:1px solid var(--border);background:var(--card);backdrop-filter:blur(14px);position:relative;z-index:5}.topbar{max-width:1240px;margin:auto;display:flex;align-items:center;justify-content:space-between;gap:16px}.brand{display:flex;align-items:center;gap:12px;min-width:0}.logo{width:46px;height:46px;border-radius:17px;background:linear-gradient(135deg,var(--primary),var(--primary2));color:#fff;display:grid;place-items:center;font-size:22px;font-weight:900;box-shadow:0 12px 26px rgba(249,115,22,.25);flex:none}h1{margin:0;color:var(--dark);font-size:clamp(22px,3vw,35px);letter-spacing:-.8px;line-height:1.08}.brand small{display:block;margin-top:4px;color:var(--muted);line-height:1.4}.top-actions{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}
    button,select,input{font-family:inherit}button{border:0;cursor:pointer;border-radius:999px;padding:11px 15px;font-weight:900;font-size:14px;transition:.18s ease;user-select:none}button:hover{transform:translateY(-1px)}button:active{transform:scale(.98)}button:disabled{opacity:.72;cursor:not-allowed}.primary{background:linear-gradient(135deg,var(--primary),var(--primary2));color:#fff;box-shadow:0 12px 26px rgba(249,115,22,.22)}.secondary{background:var(--soft);color:var(--text);border:1px solid var(--border)}.danger{background:var(--redSoft);color:#991b1b;border:1px solid #fecaca}.ghost{background:transparent;color:var(--muted);border:1px dashed var(--border)}
    main{max-width:1240px;margin:18px auto 56px;padding:0 18px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin-bottom:14px}.stat{background:var(--card);border:1px solid var(--border);border-radius:22px;padding:14px;box-shadow:0 10px 26px rgba(15,23,42,.06)}.stat b{display:block;font-size:24px;color:var(--primary);line-height:1;margin-bottom:5px}.stat span{color:var(--muted);font-size:13px}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px}.tab{background:var(--card);color:var(--text);border:1px solid var(--border);box-shadow:0 8px 20px rgba(15,23,42,.05)}.tab.active{background:var(--primary);color:#fff;border-color:var(--primary)}
    .layout{display:grid;grid-template-columns:320px 1fr;gap:16px;align-items:start}.panel,.card{background:var(--card);border:1px solid var(--border);border-radius:var(--radius);box-shadow:var(--shadow)}.panel{padding:16px;position:sticky;top:16px}.panel h2,.card h2{margin:0 0 14px;color:var(--dark);font-size:20px}.label{display:block;margin:13px 0 7px;font-weight:900;font-size:13px;color:var(--dark)}select,input{width:100%;border:1px solid var(--border);background:var(--soft);color:var(--text);border-radius:15px;padding:11px 12px;outline:none;font-size:14px}select:focus,input:focus{border-color:#fdba74;box-shadow:0 0 0 4px rgba(249,115,22,.14)}.btn-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:13px}.score-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:14px}.score{background:var(--soft);border:1px solid var(--border);border-radius:16px;text-align:center;padding:10px 6px}.score b{display:block;font-size:20px;color:var(--primary)}.score span{font-size:12px;color:var(--muted)}.progress-wrap{margin-top:12px;height:12px;border-radius:999px;background:var(--soft);border:1px solid var(--border);overflow:hidden}.progress{height:100%;width:0%;background:linear-gradient(90deg,var(--primary),var(--primary2));transition:.25s}.note{margin:12px 0 0;color:var(--muted);font-size:13px;line-height:1.5}
    .view{display:none}.view.active{display:block;animation:fadeIn .22s ease}@keyframes fadeIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}.section{padding:18px}.quiz{padding:20px;min-height:500px}.toprow{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap;margin-bottom:14px}.badges{display:flex;gap:7px;flex-wrap:wrap}.badge{display:inline-flex;align-items:center;border-radius:999px;padding:7px 10px;font-size:12px;font-weight:900;background:var(--soft);color:var(--muted);border:1px solid var(--border)}.badge.orange{background:#fff7ed;color:#c2410c;border-color:#fed7aa}.badge.green{background:var(--greenSoft);color:#166534;border-color:#86efac}.badge.red{background:var(--redSoft);color:#991b1b;border-color:#fecaca}.qno{color:var(--muted);font-size:13px;font-weight:900}.qbox{background:linear-gradient(135deg,#fff7ed,#fff);border:1px solid #fed7aa;border-radius:24px;padding:18px;margin-bottom:14px}.qtype{color:var(--primary);font-weight:900;font-size:13px;margin-bottom:8px}.qtext{white-space:pre-line;font-size:clamp(19px,2.35vw,28px);line-height:1.36;font-weight:900;color:var(--dark)}.qhint{color:var(--muted);margin-top:10px;line-height:1.5;font-size:14px}.options{display:grid;grid-template-columns:repeat(2,1fr);gap:11px;margin:14px 0}.option{background:var(--soft);color:var(--text);border:1px solid var(--border);border-radius:18px;text-align:left;line-height:1.45;font-weight:800;padding:15px;min-height:72px}.option:hover:not(:disabled){background:#fff7ed;border-color:#fdba74}.option.correct{background:var(--greenSoft);color:#166534;border-color:#86efac}.option.wrong{background:var(--redSoft);color:#991b1b;border-color:#fecaca}.answer{display:none;margin-top:14px;border:1px solid #bbf7d0;background:#f0fdf4;border-radius:22px;padding:16px;line-height:1.58;color:#166534}.answer.show{display:block}.answer b{color:#0f172a}.actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:14px}
    .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:14px}.info-card{padding:17px;background:var(--card);border:1px solid var(--border);border-radius:22px;box-shadow:0 10px 25px rgba(15,23,42,.06)}.info-card h3{margin:0 0 8px;color:var(--primary);font-size:18px}.info-card p,.info-card li{color:var(--muted);line-height:1.5;font-size:14px}.rule{background:var(--soft);border:1px solid var(--border);border-radius:15px;padding:10px;margin:10px 0;font-weight:800;color:var(--text)}.tags{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.tag{border-radius:999px;background:var(--soft);border:1px solid var(--border);color:var(--muted);padding:5px 8px;font-size:12px;font-weight:800}
    .flash-card{padding:24px;min-height:390px;display:grid;place-items:center;text-align:center}.flash-inner{max-width:780px;width:100%;border:1px solid #fed7aa;background:linear-gradient(135deg,#fff7ed,#fff);border-radius:30px;padding:30px}.flash-topic{display:inline-block;background:var(--primary);color:#fff;border-radius:999px;padding:7px 12px;font-size:12px;font-weight:900;margin-bottom:12px}.flash-question{font-size:clamp(24px,4vw,40px);line-height:1.25;font-weight:900;color:var(--dark)}.flash-answer{display:none;margin-top:18px;color:var(--green);font-weight:900;font-size:19px;line-height:1.5}.flash-answer.show{display:block}
    .test-grid{display:grid;gap:12px}.test-item{background:var(--card);border:1px solid var(--border);border-radius:20px;padding:15px}.test-item h3{margin:0 0 10px;color:var(--dark);font-size:16px;line-height:1.45}.test-options{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.test-options button{border-radius:14px;padding:10px;background:var(--soft);color:var(--text);border:1px solid var(--border);text-align:left}.test-options button.selected{background:var(--primary);color:white;border-color:var(--primary)}.test-options button.correct{background:var(--greenSoft);color:#166534;border-color:#86efac}.test-options button.wrong{background:var(--redSoft);color:#991b1b;border-color:#fecaca}.result{display:none;margin-bottom:14px;padding:14px;border-radius:18px;background:#f0fdf4;border:1px solid #bbf7d0;color:#166534;font-weight:800;line-height:1.55}.result.show{display:block}.timer{display:inline-flex;align-items:center;gap:6px;padding:8px 12px;border-radius:999px;background:var(--dark);color:white;font-weight:900;font-size:13px}.history{display:grid;gap:9px;max-height:320px;overflow:auto;padding-right:3px}.history-item{border:1px solid var(--border);background:var(--soft);border-radius:16px;padding:11px;line-height:1.45;font-size:13px}.history-item b{color:var(--primary)}.empty{color:var(--muted);text-align:center;padding:16px;background:var(--soft);border:1px dashed var(--border);border-radius:16px}.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:12px}.metric{padding:18px;border-radius:22px;background:var(--soft);border:1px solid var(--border)}.metric b{display:block;font-size:30px;color:var(--primary);margin-bottom:4px}.metric span{color:var(--muted)}.toast{position:fixed;right:18px;bottom:18px;background:var(--dark);color:white;padding:12px 14px;border-radius:16px;box-shadow:var(--shadow);opacity:0;transform:translateY(8px);pointer-events:none;transition:.25s ease;z-index:99;max-width:320px;font-weight:800;line-height:1.45}.toast.show{opacity:1;transform:translateY(0)}.footer{text-align:center;color:var(--muted);font-size:13px;margin-top:20px}
    @media(max-width:960px){.topbar,.layout{display:grid;grid-template-columns:1fr}.top-actions{justify-content:flex-start}.panel{position:static}.brand small{display:none}.stats{grid-template-columns:repeat(2,1fr)}}@media(max-width:640px){header{padding:12px 14px}main{padding:0 12px;margin-top:12px}.btn-grid,.score-grid,.options,.test-options,.stats{grid-template-columns:1fr}.quiz,.flash-card{padding:16px}.flash-inner{padding:22px}.logo{width:38px;height:38px;border-radius:13px;font-size:19px}.top-actions button{width:100%}.tab{flex:1 1 auto}}
  </style>
</head>
<body>
  <header>
    <div class="topbar">
      <div class="brand"><div class="logo">V</div><div><h1>Vista Exam Hub</h1><small>Ôn thi Tiếng Anh vào 10 THPT · Lý thuyết · Flashcard · Trắc nghiệm · Tìm lỗi sai · Mini Test</small></div></div>
      <div class="top-actions"><button class="secondary" onclick="toggleTheme()">🌓 Sáng/Tối</button><button class="secondary" onclick="speakCurrent()">🔊 Đọc câu</button><button class="primary" onclick="showTab('practice')">Học ngay</button></div>
    </div>
  </header>

  <main>
    <div class="stats">
      <div class="stat"><b id="statQuestions">0</b><span>Câu hỏi có thể luyện</span></div>
      <div class="stat"><b id="statTheory">0</b><span>Chủ đề lý thuyết</span></div>
      <div class="stat"><b id="statCards">0</b><span>Flashcards từ/cụm</span></div>
      <div class="stat"><b id="statAccuracy">0%</b><span>Độ chính xác</span></div>
    </div>

    <div class="tabs">
      <button class="tab active" data-tab="practice" onclick="showTab('practice')">🧠 Luyện tập</button>
      <button class="tab" data-tab="theory" onclick="showTab('theory')">📘 Lý thuyết</button>
      <button class="tab" data-tab="flash" onclick="showTab('flash')">⚡ Flashcard</button>
      <button class="tab" data-tab="vocab" onclick="showTab('vocab')">📚 Cụm từ</button>
      <button class="tab" data-tab="error" onclick="showTab('error')">🔎 Tìm lỗi sai</button>
      <button class="tab" data-tab="test" onclick="showTab('test')">📝 Mini Test</button>
      <button class="tab" data-tab="progress" onclick="showTab('progress')">📊 Tiến độ</button>
    </div>

    <div class="layout">
      <aside class="panel">
        <h2>⚙️ Bộ lọc học tập</h2>
        <label class="label" for="bankSelect">Ngân hàng</label>
        <select id="bankSelect" onchange="refreshAll()"><option value="all">Tất cả</option><option value="grammar">Ngữ pháp</option><option value="vocab">Từ vựng/cụm từ</option><option value="error">Tìm lỗi sai</option></select>
        <label class="label" for="topicSelect">Chủ đề</label>
        <select id="topicSelect" onchange="refreshAll()"><option value="all">Tất cả chủ đề</option></select>
        <label class="label" for="levelSelect">Mức độ</label>
        <select id="levelSelect" onchange="refreshAll()"><option value="all">Tất cả</option><option value="Nhận biết">Nhận biết</option><option value="Thông hiểu">Thông hiểu</option><option value="Vận dụng">Vận dụng</option><option value="Từ vựng">Từ vựng</option></select>
        <label class="label" for="searchInput">Tìm kiếm</label>
        <input id="searchInput" placeholder="VD: wish, passive, look after..." oninput="refreshAll()" />
        <label class="label" for="testSize">Số câu Mini Test</label>
        <select id="testSize"><option value="10">10 câu</option><option value="20" selected>20 câu</option><option value="40">40 câu</option></select>
        <div class="btn-grid"><button class="primary" onclick="nextPractice()">🎲 Random</button><button class="secondary" onclick="showAnswer()">👀 Đáp án</button><button class="secondary" onclick="newFlashcard()">⚡ Thẻ mới</button><button class="danger" onclick="resetProgress()">↺ Xóa điểm</button></div>
        <div class="score-grid"><div class="score"><b id="correctCount">0</b><span>Đúng</span></div><div class="score"><b id="wrongCount">0</b><span>Sai</span></div><div class="score"><b id="accuracyCount">0%</b><span>Tỉ lệ</span></div></div>
        <div class="progress-wrap"><div class="progress" id="progressBar"></div></div>
        <p class="note">Phím tắt: 1-4 chọn A-D, Enter sang câu mới, H xem đáp án. Tiến độ được lưu trên trình duyệt.</p>
      </aside>

      <section>
        <div id="practiceView" class="view active">
          <div class="card quiz"><div class="toprow"><div class="badges"><span class="badge orange" id="pTopic">Chủ đề</span><span class="badge" id="pLevel">Mức độ</span><span class="badge green" id="pType">4 đáp án</span></div><div class="qno" id="pNo">Câu #1</div></div><div class="qbox"><div class="qtype" id="pQType">Choose the best answer.</div><div class="qtext" id="pQuestion">Đang tải...</div><div class="qhint" id="pHint">Chọn đáp án đúng nhất.</div></div><div id="pOptions" class="options"></div><div id="pAnswer" class="answer"><b id="pAnswerMain"></b><div id="pExplain"></div></div><div class="actions"><button class="primary" onclick="nextPractice()">Câu tiếp theo</button><button class="secondary" onclick="showAnswer()">Xem đáp án</button><button class="ghost" onclick="bookmarkCurrent()">☆ Lưu câu</button></div></div>
          <div class="card section" style="margin-top:14px"><h2>📌 Lịch sử làm bài</h2><div id="historyList" class="history"><div class="empty">Chưa có câu hỏi nào.</div></div></div>
        </div>

        <div id="theoryView" class="view"><div class="card section"><h2>📘 Lý thuyết ngữ pháp vào 10</h2><div id="theoryGrid" class="grid"></div></div></div>
        <div id="flashView" class="view"><div class="card flash-card"><div class="flash-inner"><div class="flash-topic" id="flashTopic">Flashcard</div><div class="flash-question" id="flashQuestion">Bấm thẻ mới để bắt đầu</div><div class="flash-answer" id="flashAnswer"></div><div class="actions" style="justify-content:center"><button class="primary" onclick="newFlashcard()">Thẻ mới</button><button class="secondary" onclick="flipFlashcard()">Lật thẻ</button><button class="secondary" onclick="speakFlash()">Đọc thẻ</button></div></div></div></div>
        <div id="vocabView" class="view"><div class="card section"><div class="toprow"><h2 style="margin:0">📚 Cụm từ trọng tâm</h2><button class="primary" onclick="startVocabPractice()">Luyện nghĩa từ</button></div><div id="vocabGrid" class="grid"></div></div></div>
        <div id="errorView" class="view"><div class="card quiz"><div class="toprow"><div class="badges"><span class="badge orange" id="eTopic">Tìm lỗi sai</span><span class="badge" id="eLevel">Mức độ</span><span class="badge red">Error correction</span></div><div class="qno" id="eNo">Câu lỗi sai</div></div><div class="qbox"><div class="qtype">Mark the letter A, B, C or D to indicate the underlined part that needs correction.</div><div class="qtext" id="eQuestion">Đang tải...</div><div class="qhint">Chọn vị trí sai A/B/C/D, sau đó xem cách sửa.</div></div><div id="eOptions" class="options"></div><div id="eAnswer" class="answer"><b id="eAnswerMain"></b><div id="eExplain"></div></div><div class="actions"><button class="primary" onclick="nextError()">Câu lỗi sai tiếp theo</button><button class="secondary" onclick="showErrorAnswer()">Xem đáp án</button></div></div></div>
        <div id="testView" class="view"><div class="card section"><div class="toprow"><h2 style="margin:0">📝 Mini Test Generator</h2><span class="timer" id="testTimer">⏱ Chưa bắt đầu</span><div class="actions" style="margin:0"><button class="primary" onclick="createTest(true)">Tạo đề mới</button><button class="secondary" onclick="submitTest()">Nộp bài</button></div></div><div id="testResult" class="result"></div><div id="testGrid" class="test-grid"></div></div></div>
        <div id="progressView" class="view"><div class="card section"><h2>📊 Tiến độ học tập</h2><div class="metrics"><div class="metric"><b id="mDone">0</b><span>Tổng câu đã làm</span></div><div class="metric"><b id="mAccuracy">0%</b><span>Tỉ lệ đúng</span></div><div class="metric"><b id="mStreak">0</b><span>Chuỗi đúng hiện tại</span></div><div class="metric"><b id="mBest">0</b><span>Chuỗi đúng cao nhất</span></div></div><div style="margin-top:14px"><h2>Câu đã lưu</h2><div id="bookmarkList" class="history"><div class="empty">Chưa lưu câu nào.</div></div></div></div></div>
        <div class="footer">© Vista Learning Hub · Web app HTML độc lập · Sẵn sàng deploy Netlify/GitHub Pages.</div>
      </section>
    </div>
  </main>

  <div id="toast" class="toast"></div>

  <script>
    const topics=[
      {id:'Tenses',name:'Thì động từ',rule:'Chọn thì dựa vào dấu hiệu thời gian, bản chất hành động và quan hệ trước - sau.',formula:['HTĐ: S + V/Vs/es','HTTD: S + am/is/are + V-ing','HTHT: S + have/has + V3/ed','QKHT: S + had + V3/ed'],examples:['She usually goes to school.','They are playing football now.','I have learned English for five years.'],errors:['since + mốc thời gian, for + khoảng thời gian','Look!/now → hiện tại tiếp diễn','By the time + QKĐ → QKHT']},
      {id:'Passive',name:'Câu bị động',rule:'Đưa tân ngữ lên làm chủ ngữ, dùng be theo thì và V3/ed.',formula:['S + be + V3/ed','Modal + be + V3/ed','have/get + something + V3/ed'],examples:['English is spoken worldwide.','The room must be cleaned.','I had my bike repaired.'],errors:['Thiếu be','Sai V3/ed','Need + V-ing = need + to be + V3/ed']},
      {id:'Reported Speech',name:'Câu tường thuật',rule:'Đổi đại từ, lùi thì, đổi trạng từ thời gian/nơi chốn, câu hỏi về trật tự câu kể.',formula:['said that + clause','asked + O + if/whether + S + V','told + O + (not) to V'],examples:['He said he was tired.','She asked me where I lived.','He told me not to make noise.'],errors:['Không đảo câu hỏi gián tiếp','will → would','can → could']},
      {id:'Conditional & Wish',name:'Điều kiện & Wish',rule:'Loại 1 thật; loại 2 trái hiện tại; loại 3 trái quá khứ; wish diễn tả ước muốn/trái thực tế.',formula:['If + HTĐ, S + will + V','If + QKĐ, S + would/could + V','wish + S + V2/were','wish + S + had + V3'],examples:['If it rains, we will stay home.','If I were you, I would study harder.','I wish I could speak English.'],errors:['Không dùng will trong mệnh đề if','If I were you','Wish quá khứ dùng had V3']},
      {id:'Relative Clauses',name:'Mệnh đề quan hệ',rule:'Who cho người; which cho vật; where nơi chốn; when thời gian; whose sở hữu.',formula:['N + who/which/that + V','N + whose + N','where/when + S + V'],examples:['The man who lives here is kind.','The book which I bought is useful.','The girl whose father is a doctor is Lan.'],errors:['which cho người là sai','where cần mệnh đề đủ chủ vị','Rút gọn: V-ing/V3']},
      {id:'Comparison',name:'So sánh',rule:'Tính từ ngắn dùng -er/-est; tính từ dài dùng more/the most.',formula:['as + adj + as','adj-er/more adj + than','the adj-est/the most adj','The + comparative, the + comparative'],examples:['She is taller than me.','This book is more interesting.','The more you learn, the better you become.'],errors:['more taller sai','good-better-best','No one...than → so sánh nhất']},
      {id:'Verb Forms',name:'Dạng động từ',rule:'Sau từng động từ/cấu trúc có dạng V-ing, to V hoặc V nguyên thể khác nhau.',formula:['enjoy/avoid/finish/mind + V-ing','want/decide/hope + to V','make/let + O + V','would you mind + V-ing'],examples:['She enjoys reading.','My parents want me to study.','Let me help you.'],errors:['Would you mind to V sai','Sau modal dùng V nguyên thể','look forward to + V-ing']},
      {id:'Prepositions',name:'Giới từ',rule:'Học theo cụm cố định và ngữ cảnh thời gian/nơi chốn.',formula:['in + tháng/năm/mùa','on + ngày/buổi cụ thể','at + giờ/địa điểm nhỏ','adj + preposition + N/V-ing'],examples:['on Monday morning','in July','at 7 o’clock','interested in learning English'],errors:['on July sai','in Monday morning sai','since five years sai']},
      {id:'Phrases',name:'Cụm danh/động/tính',rule:'Cụm từ là phần đề hay cài lỗi: danh từ không đếm được, phrasal verbs, adjective + preposition.',formula:['adj + noun','noun + preposition + noun','verb + particle','adjective + preposition + V-ing/N'],examples:['a useful piece of advice','look after children','responsible for cleaning'],errors:['advices sai','look up children sai','responsible of sai']},
      {id:'Word Forms',name:'Từ loại',rule:'Chọn từ loại theo vị trí trong câu: danh từ, tính từ, trạng từ, động từ.',formula:['adj + noun','verb + adverb','article + noun','be + adjective/noun'],examples:['an interesting lesson','She sings beautifully.','protect the environment'],errors:['sings beautiful sai','success businessman sai','environmental sau protect sai']}
    ];

    const lexicon=[
      {cat:'Từ vựng',term:'community',meaning:'cộng đồng',type:'noun',example:'Local community activities help people connect.',tags:['local community','community service']},
      {cat:'Từ vựng',term:'facility',meaning:'cơ sở vật chất / tiện ích',type:'noun',example:'The school has modern facilities.',tags:['public facility','sports facilities']},
      {cat:'Từ vựng',term:'preserve',meaning:'bảo tồn',type:'verb',example:'We should preserve traditional crafts.',tags:['preserve culture','preserve heritage']},
      {cat:'Từ vựng',term:'heritage',meaning:'di sản',type:'noun',example:'Hoi An is famous for its cultural heritage.',tags:['cultural heritage','world heritage']},
      {cat:'Cụm danh từ',term:'entrance exam',meaning:'kỳ thi vào 10',type:'noun phrase',example:'Students are preparing for the entrance exam.',tags:['high school entrance exam','exam pressure']},
      {cat:'Cụm danh từ',term:'learning habit',meaning:'thói quen học tập',type:'noun phrase',example:'Good learning habits help students improve.',tags:['good learning habit','study plan']},
      {cat:'Cụm danh từ',term:'a piece of advice',meaning:'một lời khuyên',type:'noun phrase',example:'My teacher gave me a useful piece of advice.',tags:['useful advice','some advice']},
      {cat:'Cụm danh từ',term:'students’ performance',meaning:'kết quả học tập của học sinh',type:'noun phrase',example:'The teacher praised students’ performance.',tags:['academic performance','speaking performance']},
      {cat:'Cụm danh từ',term:'children’s mental health',meaning:'sức khỏe tinh thần của trẻ em',type:'noun phrase',example:'Parents should care about children’s mental health.',tags:['mental health','exam pressure']},
      {cat:'Phrasal verb',term:'look after',meaning:'chăm sóc',type:'phrasal verb',example:'She looks after her younger brother.',tags:['look after children','take care of']},
      {cat:'Phrasal verb',term:'look up',meaning:'tra cứu',type:'phrasal verb',example:'You should look up new words in a dictionary.',tags:['look up a word','look up information']},
      {cat:'Phrasal verb',term:'give up',meaning:'từ bỏ',type:'phrasal verb',example:'Never give up your dream.',tags:['give up smoking','give up hope']},
      {cat:'Phrasal verb',term:'find out',meaning:'tìm ra / phát hiện',type:'phrasal verb',example:'I need to find out the answer.',tags:['find out the truth','discover']},
      {cat:'Phrasal verb',term:'take part in',meaning:'tham gia',type:'phrase',example:'Many students take part in the contest.',tags:['participate in','take part in activities']},
      {cat:'Phrasal verb',term:'look forward to',meaning:'mong chờ',type:'phrase',example:'I look forward to seeing you.',tags:['look forward to V-ing','anticipate']},
      {cat:'Phrasal verb',term:'deal with',meaning:'giải quyết / xử lý',type:'phrasal verb',example:'We must deal with this problem.',tags:['deal with stress','handle problems']},
      {cat:'Cụm tính từ',term:'interested in',meaning:'hứng thú với',type:'adjective phrase',example:'She is interested in learning English.',tags:['interested in V-ing','interest']},
      {cat:'Cụm tính từ',term:'good at',meaning:'giỏi về',type:'adjective phrase',example:'He is good at Maths.',tags:['good at English','bad at']},
      {cat:'Cụm tính từ',term:'proud of',meaning:'tự hào về',type:'adjective phrase',example:'My parents are proud of me.',tags:['proud of someone','pride']},
      {cat:'Cụm tính từ',term:'responsible for',meaning:'chịu trách nhiệm về',type:'adjective phrase',example:'He is responsible for cleaning the classroom.',tags:['responsible for V-ing','responsibility']},
      {cat:'Cụm tính từ',term:'capable of',meaning:'có khả năng',type:'adjective phrase',example:'She is capable of solving the problem.',tags:['capable of V-ing','ability']},
      {cat:'Cụm tính từ',term:'suitable for',meaning:'phù hợp với',type:'adjective phrase',example:'This exercise is suitable for grade 9 students.',tags:['suitable for','appropriate for']}
    ];

    const grammarQuestions=[
      {bank:'grammar',topic:'Tenses',level:'Nhận biết',q:'She usually ______ to school by bike.',options:['go','goes','is going','went'],answer:1,explain:'Usually là dấu hiệu hiện tại đơn. She là chủ ngữ số ít nên dùng goes.'},
      {bank:'grammar',topic:'Tenses',level:'Thông hiểu',q:'I ______ English for five years.',options:['learn','learned','have learned','am learning'],answer:2,explain:'For five years dùng với hiện tại hoàn thành.'},
      {bank:'grammar',topic:'Tenses',level:'Vận dụng',q:'The last time I met him was two years ago.',options:['I met him for two years.','I have met him for two years.','I haven’t met him for two years.','I didn’t meet him since two years.'],answer:2,explain:'The last time... → haven’t/hasn’t + V3 + for + time.'},
      {bank:'grammar',topic:'Passive',level:'Nhận biết',q:'English ______ all over the world.',options:['speaks','is spoken','spoke','is speaking'],answer:1,explain:'Bị động hiện tại đơn: am/is/are + V3/ed.'},
      {bank:'grammar',topic:'Passive',level:'Thông hiểu',q:'They are building a new bridge now.',options:['A new bridge is built now.','A new bridge was built now.','A new bridge is being built now.','A new bridge has been built now.'],answer:2,explain:'Hiện tại tiếp diễn bị động: is being built.'},
      {bank:'grammar',topic:'Reported Speech',level:'Thông hiểu',q:'“Where do you live?” he asked me.',options:['He asked me where I lived.','He asked me where did I live.','He asked me where do I live.','He asked me where I live?'],answer:0,explain:'Câu hỏi gián tiếp dùng trật tự câu kể.'},
      {bank:'grammar',topic:'Conditional & Wish',level:'Nhận biết',q:'If it rains tomorrow, we ______ at home.',options:['stay','will stay','stayed','would stay'],answer:1,explain:'Điều kiện loại 1: If + HTĐ, S + will + V.'},
      {bank:'grammar',topic:'Conditional & Wish',level:'Vận dụng',q:'I didn’t go to the party last night.',options:['I wish I went to the party last night.','I wish I had gone to the party last night.','I wish I have gone to the party last night.','I wish I would go to the party last night.'],answer:1,explain:'Wish quá khứ: wish + S + had + V3/ed.'},
      {bank:'grammar',topic:'Relative Clauses',level:'Nhận biết',q:'The man ______ is standing over there is my uncle.',options:['who','which','where','when'],answer:0,explain:'Who thay cho người làm chủ ngữ.'},
      {bank:'grammar',topic:'Comparison',level:'Thông hiểu',q:'The more you practice, ______ you become.',options:['the good','the better','better','best'],answer:1,explain:'Cấu trúc so sánh kép: The + comparative, the + comparative.'},
      {bank:'grammar',topic:'Verb Forms',level:'Nhận biết',q:'She enjoys ______ books in her free time.',options:['read','to read','reading','reads'],answer:2,explain:'Enjoy + V-ing.'},
      {bank:'grammar',topic:'Prepositions',level:'Thông hiểu',q:'She is interested ______ learning English.',options:['in','on','at','for'],answer:0,explain:'Interested in + N/V-ing.'},
      {bank:'grammar',topic:'Phrases',level:'Thông hiểu',q:'Choose the correct phrase.',options:['look up children','look after children','look after a word','give out smoking'],answer:1,explain:'Look after children = chăm sóc trẻ em.'},
      {bank:'grammar',topic:'Word Forms',level:'Vận dụng',q:'She sings very ______.',options:['beautiful','beauty','beautifully','beautify'],answer:2,explain:'Sings là động từ nên cần trạng từ beautifully.'}
    ];

    const errorQuestions=[
      {bank:'error',topic:'Tenses',level:'Nhận biết',q:'She (A) usually go to school (B) by bike (C) every day (D) after breakfast.',options:['A','B','C','D'],answer:0,correction:'usually goes',explain:'Hiện tại đơn với She: động từ thêm -s/es.'},
      {bank:'error',topic:'Passive',level:'Thông hiểu',q:'English (A) speaks all over the world (B) by many people (C) nowadays (D) as a global language.',options:['A','B','C','D'],answer:0,correction:'is spoken',explain:'English là đối tượng được nói → bị động.'},
      {bank:'error',topic:'Reported Speech',level:'Thông hiểu',q:'The teacher asked me (A) where did I live (B) when I was (C) in grade 8 (D) last year.',options:['A','B','C','D'],answer:0,correction:'where I lived',explain:'Câu hỏi gián tiếp không đảo trợ động từ.'},
      {bank:'error',topic:'Conditional & Wish',level:'Nhận biết',q:'If it (A) will rain tomorrow, we (B) will stay at home (C) and watch TV (D) together.',options:['A','B','C','D'],answer:0,correction:'rains',explain:'Mệnh đề if loại 1 không dùng will.'},
      {bank:'error',topic:'Relative Clauses',level:'Nhận biết',q:'The man (A) which is standing (B) over there (C) is my English teacher (D) from Vista.',options:['A','B','C','D'],answer:0,correction:'who/that',explain:'Người dùng who/that, không dùng which.'},
      {bank:'error',topic:'Comparison',level:'Nhận biết',q:'This exercise is (A) more easier than (B) the one (C) we did (D) yesterday.',options:['A','B','C','D'],answer:0,correction:'easier',explain:'Không dùng more + tính từ ngắn thêm -er.'},
      {bank:'error',topic:'Phrases',level:'Thông hiểu',q:'My mother asked me to look (A) up my younger brother (B) while she was (C) cooking dinner (D) in the kitchen.',options:['A','B','C','D'],answer:0,correction:'look after',explain:'look after = chăm sóc; look up = tra cứu.'},
      {bank:'error',topic:'Phrases',level:'Thông hiểu',q:'She is interested (A) on learning English (B) because it is (C) useful for (D) her future.',options:['A','B','C','D'],answer:0,correction:'in learning',explain:'interested in + V-ing.'},
      {bank:'error',topic:'Phrases',level:'Vận dụng',q:'She gave me (A) some useful advices (B) before the exam (C) last week (D) at school.',options:['A','B','C','D'],answer:0,correction:'some useful advice / a useful piece of advice',explain:'Advice là danh từ không đếm được.'},
      {bank:'error',topic:'Word Forms',level:'Thông hiểu',q:'He is a very (A) success businessman (B) in my hometown (C) although (D) he is young.',options:['A','B','C','D'],answer:0,correction:'successful',explain:'Trước danh từ businessman cần tính từ.'}
    ];

    function buildVocabQuestions(){const meanings=lexicon.map(x=>x.meaning),terms=lexicon.map(x=>x.term);return lexicon.flatMap(item=>[
      {bank:'vocab',topic:'Phrases',level:'Từ vựng',q:`“${item.term}” nghĩa là gì?`,options:shuffle([item.meaning,...shuffle(meanings.filter(x=>x!==item.meaning)).slice(0,3)]),answer:null,explain:`${item.term} = ${item.meaning}. Ví dụ: ${item.example}`},
      {bank:'vocab',topic:'Phrases',level:'Từ vựng',q:`Chọn từ/cụm tiếng Anh cho nghĩa: “${item.meaning}”.`,options:shuffle([item.term,...shuffle(terms.filter(x=>x!==item.term)).slice(0,3)]),answer:null,explain:`“${item.meaning}” = ${item.term}. Cụm liên quan: ${item.tags.join(', ')}.`}
    ].map(q=>({...q,answer:q.options.indexOf(q.q.includes('nghĩa là gì')?item.meaning:item.term)})));}

    const vocabQuestions=buildVocabQuestions();
    const allQuestions=[...grammarQuestions,...vocabQuestions];
    const allPractice=[...allQuestions,...errorQuestions];
    const state={current:null,currentMode:'practice',currentError:null,answered:false,errorAnswered:false,index:0,errorIndex:0,history:[],bookmarks:loadJSON('vistaBookmarks',[]),score:loadJSON('vistaScore',{correct:0,wrong:0,streak:0,best:0}),test:[],testAnswers:{},testSubmitted:false,timer:null,seconds:0};
    const $=id=>document.getElementById(id);

    function init(){document.documentElement.dataset.theme=localStorage.getItem('vistaTheme')||'light';topics.forEach(t=>{const o=document.createElement('option');o.value=t.id;o.textContent=t.name;$('topicSelect').appendChild(o)});updateStats();renderTheory();renderVocab();nextPractice();nextError();newFlashcard();createTest(false);renderHistory();renderBookmarks();setupKeys();toast('Web app đã sẵn sàng luyện thi vào 10.');}
    function showTab(tab){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(tab+'View').classList.add('active');document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));if(tab==='theory')renderTheory();if(tab==='vocab')renderVocab();if(tab==='flash')newFlashcard();if(tab==='error')nextError();if(tab==='progress')renderProgress();}
    function refreshAll(){renderTheory();renderVocab();nextPractice();nextError();newFlashcard();createTest(false)}
    function filterQuestion(q){const bank=$('bankSelect').value,topic=$('topicSelect').value,level=$('levelSelect').value,kw=$('searchInput').value.trim().toLowerCase();const text=`${q.q} ${q.options.join(' ')} ${q.explain||''} ${q.topic} ${q.level}`.toLowerCase();return (bank==='all'||q.bank===bank)&&(topic==='all'||q.topic===topic)&&(level==='all'||q.level===level)&&(!kw||text.includes(kw));}
    function getPracticeBank(){const bank=$('bankSelect').value==='error'?errorQuestions:allQuestions;return bank.filter(filterQuestion)}
    function nextPractice(){const bank=getPracticeBank();state.answered=false;$('pAnswer').classList.remove('show');if(!bank.length){$('pQuestion').textContent='Không có câu hỏi phù hợp bộ lọc.';$('pOptions').innerHTML='';return}state.current=bank[Math.floor(Math.random()*bank.length)];state.index++;renderCurrent(state.current,'p');}
    function renderCurrent(q,prefix){$(prefix+'Topic').textContent=topicName(q.topic);$(prefix+'Level').textContent=q.level;$(prefix+'Type').textContent=q.bank==='vocab'?'Từ vựng':'Ngữ pháp';$(prefix+'No').textContent=`Câu #${state.index}`;$(prefix+'Question').textContent=q.q;$(prefix+'Hint').textContent=q.bank==='vocab'?'Mini test dạng: từ này nghĩa là gì / chọn từ đúng.':'Chọn đáp án đúng nhất.';$(prefix+'AnswerMain').textContent=`Đáp án: ${letter(q.answer)}. ${q.options[q.answer]}`;$(prefix+'Explain').textContent=q.explain;const box=$(prefix+'Options');box.innerHTML='';q.options.forEach((op,i)=>{const b=document.createElement('button');b.className='option';b.textContent=`${letter(i)}. ${op}`;b.onclick=()=>choosePractice(i);box.appendChild(b)});}
    function choosePractice(i){if(state.answered||!state.current)return;state.answered=true;const ok=i===state.current.answer;if(ok){state.score.correct++;state.score.streak++;state.score.best=Math.max(state.score.best,state.score.streak);toast('Chính xác!')}else{state.score.wrong++;state.score.streak=0;toast('Chưa đúng, xem giải thích nhé.')}document.querySelectorAll('#pOptions .option').forEach((b,idx)=>{b.disabled=true;if(idx===state.current.answer)b.classList.add('correct');if(idx===i&&!ok)b.classList.add('wrong')});showAnswer();addHistory(state.current,i,ok);saveJSON('vistaScore',state.score);updateStats();}
    function showAnswer(){if(state.current)$('pAnswer').classList.add('show')}
    function nextError(){const bank=errorQuestions.filter(filterQuestion);state.errorAnswered=false;$('eAnswer').classList.remove('show');if(!bank.length){$('eQuestion').textContent='Không có câu tìm lỗi sai phù hợp.';$('eOptions').innerHTML='';return}state.currentError=bank[Math.floor(Math.random()*bank.length)];state.errorIndex++;$('eTopic').textContent=topicName(state.currentError.topic);$('eLevel').textContent=state.currentError.level;$('eNo').textContent=`Câu lỗi sai #${state.errorIndex}`;$('eQuestion').textContent=state.currentError.q;$('eAnswerMain').textContent=`Đáp án: ${letter(state.currentError.answer)} → ${state.currentError.correction}`;$('eExplain').textContent=state.currentError.explain;$('eOptions').innerHTML='';state.currentError.options.forEach((op,i)=>{const b=document.createElement('button');b.className='option';b.textContent=`${letter(i)}. Vị trí ${op}`;b.onclick=()=>chooseError(i);$('eOptions').appendChild(b)});}
    function chooseError(i){if(state.errorAnswered||!state.currentError)return;state.errorAnswered=true;const ok=i===state.currentError.answer;if(ok){state.score.correct++;state.score.streak++;state.score.best=Math.max(state.score.best,state.score.streak);toast('Đúng lỗi sai!')}else{state.score.wrong++;state.score.streak=0;toast('Chưa đúng vị trí lỗi.')}document.querySelectorAll('#eOptions .option').forEach((b,idx)=>{b.disabled=true;if(idx===state.currentError.answer)b.classList.add('correct');if(idx===i&&!ok)b.classList.add('wrong')});showErrorAnswer();addHistory(state.currentError,i,ok);saveJSON('vistaScore',state.score);updateStats();}
    function showErrorAnswer(){if(state.currentError)$('eAnswer').classList.add('show')}
    function renderTheory(){const topic=$('topicSelect').value;const list=topic==='all'?topics:topics.filter(t=>t.id===topic);$('theoryGrid').innerHTML=list.map(t=>`<div class="info-card"><h3>${esc(t.name)}</h3><div class="rule">${esc(t.rule)}</div><p><b>Công thức:</b></p><ul>${t.formula.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p><b>Ví dụ:</b></p><ul>${t.examples.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p><b>Lỗi hay gặp:</b></p><ul>${t.errors.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><button class="secondary" onclick="setTopic('${t.id}')">Luyện chủ đề này</button></div>`).join('');}
    function setTopic(t){$('topicSelect').value=t;$('bankSelect').value='grammar';showTab('practice');nextPractice();}
    function renderVocab(){const kw=$('searchInput').value.trim().toLowerCase();const list=lexicon.filter(x=>!kw||`${x.term} ${x.meaning} ${x.cat} ${x.type} ${x.example} ${x.tags.join(' ')}`.toLowerCase().includes(kw));$('vocabGrid').innerHTML=list.map(v=>`<div class="info-card"><h3>${esc(v.term)}</h3><p><b>Nhóm:</b> ${esc(v.cat)} · <b>Từ loại:</b> ${esc(v.type)}</p><p><b>Nghĩa:</b> ${esc(v.meaning)}</p><p><b>Ví dụ:</b> ${esc(v.example)}</p><div class="tags">${v.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></div>`).join('')||'<div class="empty">Không tìm thấy cụm từ phù hợp.</div>';}
    function startVocabPractice(){$('bankSelect').value='vocab';$('topicSelect').value='all';showTab('practice');nextPractice();}
    function newFlashcard(){const list=lexicon.filter(x=>!$('searchInput').value||`${x.term} ${x.meaning} ${x.cat}`.toLowerCase().includes($('searchInput').value.toLowerCase()));const item=(list.length?list:lexicon)[Math.floor(Math.random()*(list.length?list.length:lexicon.length))];$('flashTopic').textContent=item.cat;$('flashQuestion').textContent=item.term;$('flashAnswer').textContent=`${item.meaning} · ${item.type}. Ví dụ: ${item.example}`;$('flashAnswer').classList.remove('show');}
    function flipFlashcard(){$('flashAnswer').classList.toggle('show')}
    function speakFlash(){speak(`${$('flashQuestion').textContent}. ${$('flashAnswer').textContent}`)}
    function createTest(show=true){stopTimer();state.testAnswers={};state.testSubmitted=false;const size=Number($('testSize').value||20);const bank=shuffle(allPractice.filter(filterQuestion));state.test=bank.slice(0,Math.min(size,bank.length));$('testResult').classList.remove('show');if(!state.test.length){$('testGrid').innerHTML='<div class="empty">Không có câu phù hợp để tạo đề.</div>';return}$('testGrid').innerHTML=state.test.map((q,i)=>`<div class="test-item"><h3>${i+1}. ${esc(q.q)}</h3><div class="test-options">${q.options.map((o,idx)=>`<button id="t-${i}-${idx}" onclick="chooseTest(${i},${idx})">${letter(idx)}. ${esc(o)}</button>`).join('')}</div></div>`).join('');startTimer(state.test.length);if(show)toast(`Đã tạo mini test ${state.test.length} câu.`);}
    function chooseTest(i,ans){if(state.testSubmitted)return;state.testAnswers[i]=ans;state.test[i].options.forEach((_,idx)=>{$(`t-${i}-${idx}`).classList.toggle('selected',idx===ans)});}
    function submitTest(){if(!state.test.length||state.testSubmitted)return;state.testSubmitted=true;stopTimer();let correct=0;state.test.forEach((q,i)=>{if(state.testAnswers[i]===q.answer)correct++;q.options.forEach((_,idx)=>{const b=$(`t-${i}-${idx}`);if(!b)return;b.disabled=true;if(idx===q.answer)b.classList.add('correct');if(state.testAnswers[i]===idx&&idx!==q.answer)b.classList.add('wrong')});});const percent=Math.round(correct/state.test.length*100);$('testResult').innerHTML=`Kết quả: ${correct}/${state.test.length} câu đúng (${percent}%). ${percent>=85?'Rất tốt!':percent>=65?'Khá ổn, cần xem lại câu sai.':'Cần ôn lại lý thuyết và làm lại mini test.'}`;$('testResult').classList.add('show');toast('Đã chấm xong mini test.');}
    function startTimer(count){state.seconds=Math.max(300,count*45);updateTimer();state.timer=setInterval(()=>{state.seconds--;updateTimer();if(state.seconds<=0){stopTimer();toast('Hết giờ, tự động nộp bài.');submitTest();}},1000)}
    function stopTimer(){if(state.timer)clearInterval(state.timer);state.timer=null}
    function updateTimer(){const m=String(Math.floor(state.seconds/60)).padStart(2,'0'),s=String(state.seconds%60).padStart(2,'0');$('testTimer').textContent=`⏱ ${m}:${s}`}
    function addHistory(q,ans,ok){state.history.unshift({q:q.q,topic:topicName(q.topic),ans:letter(ans),correct:letter(q.answer),ok});state.history=state.history.slice(0,14);renderHistory();}
    function renderHistory(){$('historyList').innerHTML=state.history.length?state.history.map((h,i)=>`<div class="history-item"><b>${i+1}. ${esc(h.topic)} - ${h.ok?'Đúng':'Sai'}</b><br>${esc(h.q)}<br><span style="color:var(--muted)">Bạn chọn: ${h.ans} · Đáp án: ${h.correct}</span></div>`).join(''):'<div class="empty">Chưa có câu hỏi nào.</div>';}
    function bookmarkCurrent(){if(!state.current)return;state.bookmarks.unshift({q:state.current.q,answer:letter(state.current.answer),explain:state.current.explain,topic:topicName(state.current.topic)});state.bookmarks=state.bookmarks.slice(0,30);saveJSON('vistaBookmarks',state.bookmarks);renderBookmarks();toast('Đã lưu câu hỏi.');}
    function renderBookmarks(){$('bookmarkList').innerHTML=state.bookmarks.length?state.bookmarks.map((b,i)=>`<div class="history-item"><b>${i+1}. ${esc(b.topic)}</b><br>${esc(b.q)}<br><span style="color:var(--muted)">Đáp án: ${b.answer}</span></div>`).join(''):'<div class="empty">Chưa lưu câu nào.</div>';}
    function renderProgress(){const total=state.score.correct+state.score.wrong,acc=total?Math.round(state.score.correct/total*100):0;$('mDone').textContent=total;$('mAccuracy').textContent=acc+'%';$('mStreak').textContent=state.score.streak;$('mBest').textContent=state.score.best;renderBookmarks();}
    function updateStats(){const total=state.score.correct+state.score.wrong,acc=total?Math.round(state.score.correct/total*100):0;$('statQuestions').textContent=allPractice.length;$('statTheory').textContent=topics.length;$('statCards').textContent=lexicon.length;$('statAccuracy').textContent=acc+'%';$('correctCount').textContent=state.score.correct;$('wrongCount').textContent=state.score.wrong;$('accuracyCount').textContent=acc+'%';$('progressBar').style.width=acc+'%';renderProgress();}
    function resetProgress(){if(!confirm('Xóa toàn bộ điểm và câu đã lưu trên trình duyệt này?'))return;state.score={correct:0,wrong:0,streak:0,best:0};state.history=[];state.bookmarks=[];saveJSON('vistaScore',state.score);saveJSON('vistaBookmarks',state.bookmarks);updateStats();renderHistory();renderBookmarks();toast('Đã xóa tiến độ.');}
    function toggleTheme(){const html=document.documentElement;html.dataset.theme=html.dataset.theme==='dark'?'light':'dark';localStorage.setItem('vistaTheme',html.dataset.theme)}
    function speakCurrent(){if(state.current){const text=state.current.q+'. '+state.current.options.map((o,i)=>`${letter(i)}. ${o}`).join('. ');speak(text)}}
    function speak(text){if(!('speechSynthesis'in window)){alert('Trình duyệt chưa hỗ trợ đọc tự động.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text.replace(/______/g,'blank'));u.lang='en-US';u.rate=.82;speechSynthesis.speak(u)}
    function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').classList.remove('show'),2200)}
    function saveJSON(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}
    function loadJSON(k,f){try{return JSON.parse(localStorage.getItem(k))||f}catch(e){return f}}
    function esc(t){return String(t).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
    function letter(i){return String.fromCharCode(65+i)}function topicName(id){const t=topics.find(x=>x.id===id);return t?t.name:id}
    function setupKeys(){document.addEventListener('keydown',e=>{const tag=document.activeElement.tagName.toLowerCase();if(tag==='input'||tag==='select')return;if(['1','2','3','4'].includes(e.key))choosePractice(Number(e.key)-1);if(e.key==='Enter')nextPractice();if(e.key.toLowerCase()==='h')showAnswer();});}
    init();
  </script>
</body>
</html>
